on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  linux:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        sundials_version: [2.7.0, 3.2.0, 7.1.1]
    steps:
      - uses: actions/checkout@v4
      - uses: docker/build-push-action@v6
      - name: Install make
        run: sudo apt install make -y
      - name: Build image
        run: make build-dev-image SUNDIALS_VERSION=${{ matrix.sundials_version }}
      - name: Build
        run: make build SUNDIALS_VERSION=${{ matrix.sundials_version }}
      - name: Test
        run: make test SUNDIALS_VERSION=${{ matrix.sundials_version }}
